# Generated by Django 4.0 on 2024-05-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0007_alter_airesponse_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageElement',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
